version: '3.2'
 
services:
 elasticsearch:
   build:
     context: elasticsearch/
   image: mamazary/elasticstack
   volumes:
     - type: volume
       source: elasticsearch
       target: /usr/share/elasticsearch/data
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
     discovery.type: single-node
   networks:
     - elk_stack
     - internal_network
 
 logstash:
   build:
     context: logstash/
   image: mamazary/logstash
   ports:
     - "5000:5000"
     - "9600:9600"
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
     ELASTIC_USERNAME: ${ELASTIC_USERNAME}
     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
   networks:
     - elk_stack
     - internal_network
   depends_on:
     - elasticsearch
 
 kibana:
   build:
     context: kibana/
   image: mamazary/kibana
   environment:
     ELASTIC_USERNAME: ${ELASTIC_USERNAME}
     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
   ports:
     - "5601:5601"
   networks:
     - elk_stack
     - internal_network
   depends_on:
     - elasticsearch
 
networks:
 elk_stack:
   driver: bridge
 internal_network:
   external: true
 
volumes:
 elasticsearch:
