filebeat.inputs:
- type: log
  enabled: true
  paths:
   - /var/log/jenkins/jenkins.log
  exclude_files: ['.gz$']
  multiline.pattern: '^[a-zA-Z]+\s[0-9]{1,2},\s[0-9]{4}\s[0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2}\s(?:AM|am|PM|pm)'
  multiline.negate: true
  multiline.match: after
  fields:
    type: jenkins-server
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5000"]
  bulk_max_size: 200

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
